/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.swirepay.client.model.Currency;
import com.swirepay.client.model.Plan;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubscriptionButton
 */
public class SubscriptionButtonTest {
    private final SubscriptionButton model = new SubscriptionButton();

    /**
     * Model tests for SubscriptionButton
     */
    @Test
    public void testSubscriptionButton() {
        // TODO: test SubscriptionButton
    }

    /**
     * Test the property 'gid'
     */
    @Test
    public void gidTest() {
        // TODO: test gid
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'planQuantity'
     */
    @Test
    public void planQuantityTest() {
        // TODO: test planQuantity
    }

    /**
     * Test the property 'planTotalPayments'
     */
    @Test
    public void planTotalPaymentsTest() {
        // TODO: test planTotalPayments
    }

    /**
     * Test the property 'planAmount'
     */
    @Test
    public void planAmountTest() {
        // TODO: test planAmount
    }

    /**
     * Test the property 'planBillingFrequency'
     */
    @Test
    public void planBillingFrequencyTest() {
        // TODO: test planBillingFrequency
    }

    /**
     * Test the property 'planBillingPeriod'
     */
    @Test
    public void planBillingPeriodTest() {
        // TODO: test planBillingPeriod
    }

    /**
     * Test the property 'planStartDate'
     */
    @Test
    public void planStartDateTest() {
        // TODO: test planStartDate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'nextActionUrl'
     */
    @Test
    public void nextActionUrlTest() {
        // TODO: test nextActionUrl
    }

    /**
     * Test the property 'redirectUri'
     */
    @Test
    public void redirectUriTest() {
        // TODO: test redirectUri
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'plan'
     */
    @Test
    public void planTest() {
        // TODO: test plan
    }

}
