/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Country
 */
@JsonPropertyOrder({
  Country.JSON_PROPERTY_ALPHA2,
  Country.JSON_PROPERTY_ALPHA3,
  Country.JSON_PROPERTY_DELETED,
  Country.JSON_PROPERTY_ID,
  Country.JSON_PROPERTY_NAME,
  Country.JSON_PROPERTY_UN_CODE
})
@JsonTypeName("Country")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-05T05:48:22.419Z[Etc/UTC]")
public class Country {
  public static final String JSON_PROPERTY_ALPHA2 = "alpha2";
  private String alpha2;

  public static final String JSON_PROPERTY_ALPHA3 = "alpha3";
  private String alpha3;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_UN_CODE = "unCode";
  private String unCode;


  public Country alpha2(String alpha2) {
    
    this.alpha2 = alpha2;
    return this;
  }

   /**
   * Get alpha2
   * @return alpha2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALPHA2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlpha2() {
    return alpha2;
  }


  public void setAlpha2(String alpha2) {
    this.alpha2 = alpha2;
  }


  public Country alpha3(String alpha3) {
    
    this.alpha3 = alpha3;
    return this;
  }

   /**
   * Get alpha3
   * @return alpha3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALPHA3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlpha3() {
    return alpha3;
  }


  public void setAlpha3(String alpha3) {
    this.alpha3 = alpha3;
  }


  public Country deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public Country id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Country name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Country unCode(String unCode) {
    
    this.unCode = unCode;
    return this;
  }

   /**
   * Get unCode
   * @return unCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UN_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnCode() {
    return unCode;
  }


  public void setUnCode(String unCode) {
    this.unCode = unCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Country country = (Country) o;
    return Objects.equals(this.alpha2, country.alpha2) &&
        Objects.equals(this.alpha3, country.alpha3) &&
        Objects.equals(this.deleted, country.deleted) &&
        Objects.equals(this.id, country.id) &&
        Objects.equals(this.name, country.name) &&
        Objects.equals(this.unCode, country.unCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alpha2, alpha3, deleted, id, name, unCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Country {\n");
    sb.append("    alpha2: ").append(toIndentedString(alpha2)).append("\n");
    sb.append("    alpha3: ").append(toIndentedString(alpha3)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    unCode: ").append(toIndentedString(unCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

