/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PaymentSessionRequest
 */
@JsonPropertyOrder({
  PaymentSessionRequest.JSON_PROPERTY_AMOUNT,
  PaymentSessionRequest.JSON_PROPERTY_AMOUNT_REFUNDED,
  PaymentSessionRequest.JSON_PROPERTY_STATEMENT_DESCRIPTOR,
  PaymentSessionRequest.JSON_PROPERTY_CURRENCY_CODE,
  PaymentSessionRequest.JSON_PROPERTY_PAYMENT_METHOD_TYPE,
  PaymentSessionRequest.JSON_PROPERTY_CUSTOMER_GID,
  PaymentSessionRequest.JSON_PROPERTY_PAYMENT_METHOD_GID,
  PaymentSessionRequest.JSON_PROPERTY_DESCRIPTION,
  PaymentSessionRequest.JSON_PROPERTY_RECEIPT_EMAIL,
  PaymentSessionRequest.JSON_PROPERTY_RECEIPT_SMS,
  PaymentSessionRequest.JSON_PROPERTY_CONFIRM_METHOD,
  PaymentSessionRequest.JSON_PROPERTY_CAPTURE_METHOD,
  PaymentSessionRequest.JSON_PROPERTY_REFUND_REASON,
  PaymentSessionRequest.JSON_PROPERTY_REFUND_NOTE,
  PaymentSessionRequest.JSON_PROPERTY_RECEIPT_NUMBER,
  PaymentSessionRequest.JSON_PROPERTY_MRN
})
@JsonTypeName("PaymentSessionRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-05T05:55:44.963Z[Etc/UTC]")
public class PaymentSessionRequest {
  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Long amount;

  public static final String JSON_PROPERTY_AMOUNT_REFUNDED = "amountRefunded";
  private Long amountRefunded;

  public static final String JSON_PROPERTY_STATEMENT_DESCRIPTOR = "statementDescriptor";
  private String statementDescriptor;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  private String currencyCode;

  public static final String JSON_PROPERTY_PAYMENT_METHOD_TYPE = "paymentMethodType";
  private List<String> paymentMethodType = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOMER_GID = "customerGid";
  private String customerGid;

  public static final String JSON_PROPERTY_PAYMENT_METHOD_GID = "paymentMethodGid";
  private String paymentMethodGid;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_RECEIPT_EMAIL = "receiptEmail";
  private String receiptEmail;

  public static final String JSON_PROPERTY_RECEIPT_SMS = "receiptSms";
  private String receiptSms;

  public static final String JSON_PROPERTY_CONFIRM_METHOD = "confirmMethod";
  private String confirmMethod;

  public static final String JSON_PROPERTY_CAPTURE_METHOD = "captureMethod";
  private String captureMethod;

  public static final String JSON_PROPERTY_REFUND_REASON = "refundReason";
  private String refundReason;

  public static final String JSON_PROPERTY_REFUND_NOTE = "refundNote";
  private String refundNote;

  public static final String JSON_PROPERTY_RECEIPT_NUMBER = "receiptNumber";
  private String receiptNumber;

  public static final String JSON_PROPERTY_MRN = "mrn";
  private String mrn;


  public PaymentSessionRequest amount(Long amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAmount() {
    return amount;
  }


  public void setAmount(Long amount) {
    this.amount = amount;
  }


  public PaymentSessionRequest amountRefunded(Long amountRefunded) {
    
    this.amountRefunded = amountRefunded;
    return this;
  }

   /**
   * Get amountRefunded
   * @return amountRefunded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_REFUNDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAmountRefunded() {
    return amountRefunded;
  }


  public void setAmountRefunded(Long amountRefunded) {
    this.amountRefunded = amountRefunded;
  }


  public PaymentSessionRequest statementDescriptor(String statementDescriptor) {
    
    this.statementDescriptor = statementDescriptor;
    return this;
  }

   /**
   * Get statementDescriptor
   * @return statementDescriptor
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_STATEMENT_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatementDescriptor() {
    return statementDescriptor;
  }


  public void setStatementDescriptor(String statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
  }


  public PaymentSessionRequest currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public PaymentSessionRequest paymentMethodType(List<String> paymentMethodType) {
    
    this.paymentMethodType = paymentMethodType;
    return this;
  }

  public PaymentSessionRequest addPaymentMethodTypeItem(String paymentMethodTypeItem) {
    this.paymentMethodType.add(paymentMethodTypeItem);
    return this;
  }

   /**
   * Get paymentMethodType
   * @return paymentMethodType
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getPaymentMethodType() {
    return paymentMethodType;
  }


  public void setPaymentMethodType(List<String> paymentMethodType) {
    this.paymentMethodType = paymentMethodType;
  }


  public PaymentSessionRequest customerGid(String customerGid) {
    
    this.customerGid = customerGid;
    return this;
  }

   /**
   * Get customerGid
   * @return customerGid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOMER_GID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerGid() {
    return customerGid;
  }


  public void setCustomerGid(String customerGid) {
    this.customerGid = customerGid;
  }


  public PaymentSessionRequest paymentMethodGid(String paymentMethodGid) {
    
    this.paymentMethodGid = paymentMethodGid;
    return this;
  }

   /**
   * Get paymentMethodGid
   * @return paymentMethodGid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_GID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentMethodGid() {
    return paymentMethodGid;
  }


  public void setPaymentMethodGid(String paymentMethodGid) {
    this.paymentMethodGid = paymentMethodGid;
  }


  public PaymentSessionRequest description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PaymentSessionRequest receiptEmail(String receiptEmail) {
    
    this.receiptEmail = receiptEmail;
    return this;
  }

   /**
   * Get receiptEmail
   * @return receiptEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiptEmail() {
    return receiptEmail;
  }


  public void setReceiptEmail(String receiptEmail) {
    this.receiptEmail = receiptEmail;
  }


  public PaymentSessionRequest receiptSms(String receiptSms) {
    
    this.receiptSms = receiptSms;
    return this;
  }

   /**
   * Get receiptSms
   * @return receiptSms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_SMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiptSms() {
    return receiptSms;
  }


  public void setReceiptSms(String receiptSms) {
    this.receiptSms = receiptSms;
  }


  public PaymentSessionRequest confirmMethod(String confirmMethod) {
    
    this.confirmMethod = confirmMethod;
    return this;
  }

   /**
   * Get confirmMethod
   * @return confirmMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONFIRM_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfirmMethod() {
    return confirmMethod;
  }


  public void setConfirmMethod(String confirmMethod) {
    this.confirmMethod = confirmMethod;
  }


  public PaymentSessionRequest captureMethod(String captureMethod) {
    
    this.captureMethod = captureMethod;
    return this;
  }

   /**
   * Get captureMethod
   * @return captureMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAPTURE_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaptureMethod() {
    return captureMethod;
  }


  public void setCaptureMethod(String captureMethod) {
    this.captureMethod = captureMethod;
  }


  public PaymentSessionRequest refundReason(String refundReason) {
    
    this.refundReason = refundReason;
    return this;
  }

   /**
   * Get refundReason
   * @return refundReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFUND_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundReason() {
    return refundReason;
  }


  public void setRefundReason(String refundReason) {
    this.refundReason = refundReason;
  }


  public PaymentSessionRequest refundNote(String refundNote) {
    
    this.refundNote = refundNote;
    return this;
  }

   /**
   * Get refundNote
   * @return refundNote
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFUND_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundNote() {
    return refundNote;
  }


  public void setRefundNote(String refundNote) {
    this.refundNote = refundNote;
  }


  public PaymentSessionRequest receiptNumber(String receiptNumber) {
    
    this.receiptNumber = receiptNumber;
    return this;
  }

   /**
   * Get receiptNumber
   * @return receiptNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiptNumber() {
    return receiptNumber;
  }


  public void setReceiptNumber(String receiptNumber) {
    this.receiptNumber = receiptNumber;
  }


  public PaymentSessionRequest mrn(String mrn) {
    
    this.mrn = mrn;
    return this;
  }

   /**
   * Get mrn
   * @return mrn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MRN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMrn() {
    return mrn;
  }


  public void setMrn(String mrn) {
    this.mrn = mrn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentSessionRequest paymentSessionRequest = (PaymentSessionRequest) o;
    return Objects.equals(this.amount, paymentSessionRequest.amount) &&
        Objects.equals(this.amountRefunded, paymentSessionRequest.amountRefunded) &&
        Objects.equals(this.statementDescriptor, paymentSessionRequest.statementDescriptor) &&
        Objects.equals(this.currencyCode, paymentSessionRequest.currencyCode) &&
        Objects.equals(this.paymentMethodType, paymentSessionRequest.paymentMethodType) &&
        Objects.equals(this.customerGid, paymentSessionRequest.customerGid) &&
        Objects.equals(this.paymentMethodGid, paymentSessionRequest.paymentMethodGid) &&
        Objects.equals(this.description, paymentSessionRequest.description) &&
        Objects.equals(this.receiptEmail, paymentSessionRequest.receiptEmail) &&
        Objects.equals(this.receiptSms, paymentSessionRequest.receiptSms) &&
        Objects.equals(this.confirmMethod, paymentSessionRequest.confirmMethod) &&
        Objects.equals(this.captureMethod, paymentSessionRequest.captureMethod) &&
        Objects.equals(this.refundReason, paymentSessionRequest.refundReason) &&
        Objects.equals(this.refundNote, paymentSessionRequest.refundNote) &&
        Objects.equals(this.receiptNumber, paymentSessionRequest.receiptNumber) &&
        Objects.equals(this.mrn, paymentSessionRequest.mrn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, amountRefunded, statementDescriptor, currencyCode, paymentMethodType, customerGid, paymentMethodGid, description, receiptEmail, receiptSms, confirmMethod, captureMethod, refundReason, refundNote, receiptNumber, mrn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentSessionRequest {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amountRefunded: ").append(toIndentedString(amountRefunded)).append("\n");
    sb.append("    statementDescriptor: ").append(toIndentedString(statementDescriptor)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    paymentMethodType: ").append(toIndentedString(paymentMethodType)).append("\n");
    sb.append("    customerGid: ").append(toIndentedString(customerGid)).append("\n");
    sb.append("    paymentMethodGid: ").append(toIndentedString(paymentMethodGid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    receiptEmail: ").append(toIndentedString(receiptEmail)).append("\n");
    sb.append("    receiptSms: ").append(toIndentedString(receiptSms)).append("\n");
    sb.append("    confirmMethod: ").append(toIndentedString(confirmMethod)).append("\n");
    sb.append("    captureMethod: ").append(toIndentedString(captureMethod)).append("\n");
    sb.append("    refundReason: ").append(toIndentedString(refundReason)).append("\n");
    sb.append("    refundNote: ").append(toIndentedString(refundNote)).append("\n");
    sb.append("    receiptNumber: ").append(toIndentedString(receiptNumber)).append("\n");
    sb.append("    mrn: ").append(toIndentedString(mrn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

