/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.swirepay.client.model.CardRequest;
import com.swirepay.client.model.UpiRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PaymentMethodRequest
 */
@JsonPropertyOrder({
  PaymentMethodRequest.JSON_PROPERTY_CARD,
  PaymentMethodRequest.JSON_PROPERTY_CUSTOMER_GID,
  PaymentMethodRequest.JSON_PROPERTY_TYPE,
  PaymentMethodRequest.JSON_PROPERTY_UPI
})
@JsonTypeName("PaymentMethodRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-05T05:48:22.419Z[Etc/UTC]")
public class PaymentMethodRequest {
  public static final String JSON_PROPERTY_CARD = "card";
  private CardRequest card;

  public static final String JSON_PROPERTY_CUSTOMER_GID = "customerGid";
  private String customerGid;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_UPI = "upi";
  private UpiRequest upi;


  public PaymentMethodRequest card(CardRequest card) {
    
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CardRequest getCard() {
    return card;
  }


  public void setCard(CardRequest card) {
    this.card = card;
  }


  public PaymentMethodRequest customerGid(String customerGid) {
    
    this.customerGid = customerGid;
    return this;
  }

   /**
   * Get customerGid
   * @return customerGid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "customer-cce717534d2d4ccfa2efd1948a6bd0bd", value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOMER_GID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerGid() {
    return customerGid;
  }


  public void setCustomerGid(String customerGid) {
    this.customerGid = customerGid;
  }


  public PaymentMethodRequest type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public PaymentMethodRequest upi(UpiRequest upi) {
    
    this.upi = upi;
    return this;
  }

   /**
   * Get upi
   * @return upi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpiRequest getUpi() {
    return upi;
  }


  public void setUpi(UpiRequest upi) {
    this.upi = upi;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodRequest paymentMethodRequest = (PaymentMethodRequest) o;
    return Objects.equals(this.card, paymentMethodRequest.card) &&
        Objects.equals(this.customerGid, paymentMethodRequest.customerGid) &&
        Objects.equals(this.type, paymentMethodRequest.type) &&
        Objects.equals(this.upi, paymentMethodRequest.upi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(card, customerGid, type, upi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodRequest {\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    customerGid: ").append(toIndentedString(customerGid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    upi: ").append(toIndentedString(upi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

