/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.swirepay.client.model.AccountRate;
import com.swirepay.client.model.Currency;
import com.swirepay.client.model.Customer;
import com.swirepay.client.model.PaymentMethod;
import com.swirepay.client.model.PaymentMethodType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PaymentSession
 */
@JsonPropertyOrder({
  PaymentSession.JSON_PROPERTY_GID,
  PaymentSession.JSON_PROPERTY_CREATED_AT,
  PaymentSession.JSON_PROPERTY_UPDATED_AT,
  PaymentSession.JSON_PROPERTY_DELETED,
  PaymentSession.JSON_PROPERTY_STATUS,
  PaymentSession.JSON_PROPERTY_AMOUNT,
  PaymentSession.JSON_PROPERTY_AMOUNT_REFUNDED,
  PaymentSession.JSON_PROPERTY_AMOUNT_UN_CAPTURED,
  PaymentSession.JSON_PROPERTY_AMOUNT_RECEIVED,
  PaymentSession.JSON_PROPERTY_DESCRIPTION,
  PaymentSession.JSON_PROPERTY_STATEMENT_DESCRIPTOR,
  PaymentSession.JSON_PROPERTY_RECEIPT_EMAIL,
  PaymentSession.JSON_PROPERTY_RECEIPT_SMS,
  PaymentSession.JSON_PROPERTY_CONFIRM_METHOD,
  PaymentSession.JSON_PROPERTY_CAPTURE_METHOD,
  PaymentSession.JSON_PROPERTY_ERROR_CODE,
  PaymentSession.JSON_PROPERTY_ERROR_DESCRIPTION,
  PaymentSession.JSON_PROPERTY_REFUND_REASON,
  PaymentSession.JSON_PROPERTY_REFUND_NOTE,
  PaymentSession.JSON_PROPERTY_DISPUTE_TYPE,
  PaymentSession.JSON_PROPERTY_DISPUTE_STATUS,
  PaymentSession.JSON_PROPERTY_RESPOND_BY,
  PaymentSession.JSON_PROPERTY_PAYMENT_DATE,
  PaymentSession.JSON_PROPERTY_REFUND_DATE,
  PaymentSession.JSON_PROPERTY_DISPUTE_DATE,
  PaymentSession.JSON_PROPERTY_AMOUNT_DISPUTED,
  PaymentSession.JSON_PROPERTY_DISPUTE_FEE,
  PaymentSession.JSON_PROPERTY_FEE_AMOUNT,
  PaymentSession.JSON_PROPERTY_FEE_TAX,
  PaymentSession.JSON_PROPERTY_NET,
  PaymentSession.JSON_PROPERTY_MDR,
  PaymentSession.JSON_PROPERTY_RECEIPT_NUMBER,
  PaymentSession.JSON_PROPERTY_NEXT_ACTION_URL,
  PaymentSession.JSON_PROPERTY_PS_CLIENT_SECRET,
  PaymentSession.JSON_PROPERTY_AUTHORIZATION_ID,
  PaymentSession.JSON_PROPERTY_RETURN_URL,
  PaymentSession.JSON_PROPERTY_SECURE_STATUS,
  PaymentSession.JSON_PROPERTY_PAYMENT_LINK_ID,
  PaymentSession.JSON_PROPERTY_PAYMENT_LINK_GID,
  PaymentSession.JSON_PROPERTY_MRN,
  PaymentSession.JSON_PROPERTY_RRN,
  PaymentSession.JSON_PROPERTY_PAYMENT_METHOD_TYPE,
  PaymentSession.JSON_PROPERTY_PAYMENT_METHOD,
  PaymentSession.JSON_PROPERTY_CURRENCY,
  PaymentSession.JSON_PROPERTY_CUSTOMER,
  PaymentSession.JSON_PROPERTY_ACCOUNT_RATE
})
@JsonTypeName("PaymentSession")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-05T05:32:04.002Z[Etc/UTC]")
public class PaymentSession {
  public static final String JSON_PROPERTY_GID = "gid";
  private String gid;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private String createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private String updatedAt;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  public static final String JSON_PROPERTY_AMOUNT_REFUNDED = "amountRefunded";
  private Integer amountRefunded;

  public static final String JSON_PROPERTY_AMOUNT_UN_CAPTURED = "amountUnCaptured";
  private Integer amountUnCaptured;

  public static final String JSON_PROPERTY_AMOUNT_RECEIVED = "amountReceived";
  private Integer amountReceived;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_STATEMENT_DESCRIPTOR = "statementDescriptor";
  private String statementDescriptor;

  public static final String JSON_PROPERTY_RECEIPT_EMAIL = "receiptEmail";
  private String receiptEmail;

  public static final String JSON_PROPERTY_RECEIPT_SMS = "receiptSms";
  private String receiptSms;

  public static final String JSON_PROPERTY_CONFIRM_METHOD = "confirmMethod";
  private String confirmMethod;

  public static final String JSON_PROPERTY_CAPTURE_METHOD = "captureMethod";
  private String captureMethod;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_DESCRIPTION = "errorDescription";
  private String errorDescription;

  public static final String JSON_PROPERTY_REFUND_REASON = "refundReason";
  private String refundReason;

  public static final String JSON_PROPERTY_REFUND_NOTE = "refundNote";
  private String refundNote;

  public static final String JSON_PROPERTY_DISPUTE_TYPE = "disputeType";
  private String disputeType;

  public static final String JSON_PROPERTY_DISPUTE_STATUS = "disputeStatus";
  private String disputeStatus;

  public static final String JSON_PROPERTY_RESPOND_BY = "respondBy";
  private String respondBy;

  public static final String JSON_PROPERTY_PAYMENT_DATE = "paymentDate";
  private String paymentDate;

  public static final String JSON_PROPERTY_REFUND_DATE = "refundDate";
  private String refundDate;

  public static final String JSON_PROPERTY_DISPUTE_DATE = "disputeDate";
  private String disputeDate;

  public static final String JSON_PROPERTY_AMOUNT_DISPUTED = "amountDisputed";
  private Integer amountDisputed;

  public static final String JSON_PROPERTY_DISPUTE_FEE = "disputeFee";
  private Integer disputeFee;

  public static final String JSON_PROPERTY_FEE_AMOUNT = "feeAmount";
  private Integer feeAmount;

  public static final String JSON_PROPERTY_FEE_TAX = "feeTax";
  private Integer feeTax;

  public static final String JSON_PROPERTY_NET = "net";
  private Integer net;

  public static final String JSON_PROPERTY_MDR = "mdr";
  private String mdr;

  public static final String JSON_PROPERTY_RECEIPT_NUMBER = "receiptNumber";
  private String receiptNumber;

  public static final String JSON_PROPERTY_NEXT_ACTION_URL = "nextActionUrl";
  private String nextActionUrl;

  public static final String JSON_PROPERTY_PS_CLIENT_SECRET = "psClientSecret";
  private String psClientSecret;

  public static final String JSON_PROPERTY_AUTHORIZATION_ID = "authorizationId";
  private String authorizationId;

  public static final String JSON_PROPERTY_RETURN_URL = "returnUrl";
  private String returnUrl;

  public static final String JSON_PROPERTY_SECURE_STATUS = "secureStatus";
  private String secureStatus;

  public static final String JSON_PROPERTY_PAYMENT_LINK_ID = "paymentLinkId";
  private String paymentLinkId;

  public static final String JSON_PROPERTY_PAYMENT_LINK_GID = "paymentLinkGid";
  private String paymentLinkGid;

  public static final String JSON_PROPERTY_MRN = "mrn";
  private String mrn;

  public static final String JSON_PROPERTY_RRN = "rrn";
  private String rrn;

  public static final String JSON_PROPERTY_PAYMENT_METHOD_TYPE = "paymentMethodType";
  private List<PaymentMethodType> paymentMethodType = null;

  public static final String JSON_PROPERTY_PAYMENT_METHOD = "paymentMethod";
  private PaymentMethod paymentMethod;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private Currency currency;

  public static final String JSON_PROPERTY_CUSTOMER = "customer";
  private Customer customer;

  public static final String JSON_PROPERTY_ACCOUNT_RATE = "accountRate";
  private AccountRate accountRate;


  public PaymentSession gid(String gid) {
    
    this.gid = gid;
    return this;
  }

   /**
   * Get gid
   * @return gid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGid() {
    return gid;
  }


  public void setGid(String gid) {
    this.gid = gid;
  }


  public PaymentSession createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public PaymentSession updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public PaymentSession deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public PaymentSession status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public PaymentSession amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public PaymentSession amountRefunded(Integer amountRefunded) {
    
    this.amountRefunded = amountRefunded;
    return this;
  }

   /**
   * Get amountRefunded
   * @return amountRefunded
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_REFUNDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmountRefunded() {
    return amountRefunded;
  }


  public void setAmountRefunded(Integer amountRefunded) {
    this.amountRefunded = amountRefunded;
  }


  public PaymentSession amountUnCaptured(Integer amountUnCaptured) {
    
    this.amountUnCaptured = amountUnCaptured;
    return this;
  }

   /**
   * Get amountUnCaptured
   * @return amountUnCaptured
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_UN_CAPTURED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmountUnCaptured() {
    return amountUnCaptured;
  }


  public void setAmountUnCaptured(Integer amountUnCaptured) {
    this.amountUnCaptured = amountUnCaptured;
  }


  public PaymentSession amountReceived(Integer amountReceived) {
    
    this.amountReceived = amountReceived;
    return this;
  }

   /**
   * Get amountReceived
   * @return amountReceived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_RECEIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmountReceived() {
    return amountReceived;
  }


  public void setAmountReceived(Integer amountReceived) {
    this.amountReceived = amountReceived;
  }


  public PaymentSession description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PaymentSession statementDescriptor(String statementDescriptor) {
    
    this.statementDescriptor = statementDescriptor;
    return this;
  }

   /**
   * Get statementDescriptor
   * @return statementDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATEMENT_DESCRIPTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatementDescriptor() {
    return statementDescriptor;
  }


  public void setStatementDescriptor(String statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
  }


  public PaymentSession receiptEmail(String receiptEmail) {
    
    this.receiptEmail = receiptEmail;
    return this;
  }

   /**
   * Get receiptEmail
   * @return receiptEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiptEmail() {
    return receiptEmail;
  }


  public void setReceiptEmail(String receiptEmail) {
    this.receiptEmail = receiptEmail;
  }


  public PaymentSession receiptSms(String receiptSms) {
    
    this.receiptSms = receiptSms;
    return this;
  }

   /**
   * Get receiptSms
   * @return receiptSms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_SMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiptSms() {
    return receiptSms;
  }


  public void setReceiptSms(String receiptSms) {
    this.receiptSms = receiptSms;
  }


  public PaymentSession confirmMethod(String confirmMethod) {
    
    this.confirmMethod = confirmMethod;
    return this;
  }

   /**
   * Get confirmMethod
   * @return confirmMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONFIRM_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConfirmMethod() {
    return confirmMethod;
  }


  public void setConfirmMethod(String confirmMethod) {
    this.confirmMethod = confirmMethod;
  }


  public PaymentSession captureMethod(String captureMethod) {
    
    this.captureMethod = captureMethod;
    return this;
  }

   /**
   * Get captureMethod
   * @return captureMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAPTURE_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaptureMethod() {
    return captureMethod;
  }


  public void setCaptureMethod(String captureMethod) {
    this.captureMethod = captureMethod;
  }


  public PaymentSession errorCode(String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  public PaymentSession errorDescription(String errorDescription) {
    
    this.errorDescription = errorDescription;
    return this;
  }

   /**
   * Get errorDescription
   * @return errorDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescription() {
    return errorDescription;
  }


  public void setErrorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
  }


  public PaymentSession refundReason(String refundReason) {
    
    this.refundReason = refundReason;
    return this;
  }

   /**
   * Get refundReason
   * @return refundReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFUND_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundReason() {
    return refundReason;
  }


  public void setRefundReason(String refundReason) {
    this.refundReason = refundReason;
  }


  public PaymentSession refundNote(String refundNote) {
    
    this.refundNote = refundNote;
    return this;
  }

   /**
   * Get refundNote
   * @return refundNote
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFUND_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundNote() {
    return refundNote;
  }


  public void setRefundNote(String refundNote) {
    this.refundNote = refundNote;
  }


  public PaymentSession disputeType(String disputeType) {
    
    this.disputeType = disputeType;
    return this;
  }

   /**
   * Get disputeType
   * @return disputeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPUTE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisputeType() {
    return disputeType;
  }


  public void setDisputeType(String disputeType) {
    this.disputeType = disputeType;
  }


  public PaymentSession disputeStatus(String disputeStatus) {
    
    this.disputeStatus = disputeStatus;
    return this;
  }

   /**
   * Get disputeStatus
   * @return disputeStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPUTE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisputeStatus() {
    return disputeStatus;
  }


  public void setDisputeStatus(String disputeStatus) {
    this.disputeStatus = disputeStatus;
  }


  public PaymentSession respondBy(String respondBy) {
    
    this.respondBy = respondBy;
    return this;
  }

   /**
   * Get respondBy
   * @return respondBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESPOND_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRespondBy() {
    return respondBy;
  }


  public void setRespondBy(String respondBy) {
    this.respondBy = respondBy;
  }


  public PaymentSession paymentDate(String paymentDate) {
    
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * Get paymentDate
   * @return paymentDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentDate() {
    return paymentDate;
  }


  public void setPaymentDate(String paymentDate) {
    this.paymentDate = paymentDate;
  }


  public PaymentSession refundDate(String refundDate) {
    
    this.refundDate = refundDate;
    return this;
  }

   /**
   * Get refundDate
   * @return refundDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFUND_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRefundDate() {
    return refundDate;
  }


  public void setRefundDate(String refundDate) {
    this.refundDate = refundDate;
  }


  public PaymentSession disputeDate(String disputeDate) {
    
    this.disputeDate = disputeDate;
    return this;
  }

   /**
   * Get disputeDate
   * @return disputeDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPUTE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisputeDate() {
    return disputeDate;
  }


  public void setDisputeDate(String disputeDate) {
    this.disputeDate = disputeDate;
  }


  public PaymentSession amountDisputed(Integer amountDisputed) {
    
    this.amountDisputed = amountDisputed;
    return this;
  }

   /**
   * Get amountDisputed
   * @return amountDisputed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMOUNT_DISPUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmountDisputed() {
    return amountDisputed;
  }


  public void setAmountDisputed(Integer amountDisputed) {
    this.amountDisputed = amountDisputed;
  }


  public PaymentSession disputeFee(Integer disputeFee) {
    
    this.disputeFee = disputeFee;
    return this;
  }

   /**
   * Get disputeFee
   * @return disputeFee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPUTE_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDisputeFee() {
    return disputeFee;
  }


  public void setDisputeFee(Integer disputeFee) {
    this.disputeFee = disputeFee;
  }


  public PaymentSession feeAmount(Integer feeAmount) {
    
    this.feeAmount = feeAmount;
    return this;
  }

   /**
   * Get feeAmount
   * @return feeAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FEE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFeeAmount() {
    return feeAmount;
  }


  public void setFeeAmount(Integer feeAmount) {
    this.feeAmount = feeAmount;
  }


  public PaymentSession feeTax(Integer feeTax) {
    
    this.feeTax = feeTax;
    return this;
  }

   /**
   * Get feeTax
   * @return feeTax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FEE_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFeeTax() {
    return feeTax;
  }


  public void setFeeTax(Integer feeTax) {
    this.feeTax = feeTax;
  }


  public PaymentSession net(Integer net) {
    
    this.net = net;
    return this;
  }

   /**
   * Get net
   * @return net
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNet() {
    return net;
  }


  public void setNet(Integer net) {
    this.net = net;
  }


  public PaymentSession mdr(String mdr) {
    
    this.mdr = mdr;
    return this;
  }

   /**
   * Get mdr
   * @return mdr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MDR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMdr() {
    return mdr;
  }


  public void setMdr(String mdr) {
    this.mdr = mdr;
  }


  public PaymentSession receiptNumber(String receiptNumber) {
    
    this.receiptNumber = receiptNumber;
    return this;
  }

   /**
   * Get receiptNumber
   * @return receiptNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIPT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiptNumber() {
    return receiptNumber;
  }


  public void setReceiptNumber(String receiptNumber) {
    this.receiptNumber = receiptNumber;
  }


  public PaymentSession nextActionUrl(String nextActionUrl) {
    
    this.nextActionUrl = nextActionUrl;
    return this;
  }

   /**
   * Get nextActionUrl
   * @return nextActionUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT_ACTION_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextActionUrl() {
    return nextActionUrl;
  }


  public void setNextActionUrl(String nextActionUrl) {
    this.nextActionUrl = nextActionUrl;
  }


  public PaymentSession psClientSecret(String psClientSecret) {
    
    this.psClientSecret = psClientSecret;
    return this;
  }

   /**
   * Get psClientSecret
   * @return psClientSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PS_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPsClientSecret() {
    return psClientSecret;
  }


  public void setPsClientSecret(String psClientSecret) {
    this.psClientSecret = psClientSecret;
  }


  public PaymentSession authorizationId(String authorizationId) {
    
    this.authorizationId = authorizationId;
    return this;
  }

   /**
   * Get authorizationId
   * @return authorizationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHORIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthorizationId() {
    return authorizationId;
  }


  public void setAuthorizationId(String authorizationId) {
    this.authorizationId = authorizationId;
  }


  public PaymentSession returnUrl(String returnUrl) {
    
    this.returnUrl = returnUrl;
    return this;
  }

   /**
   * Get returnUrl
   * @return returnUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RETURN_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReturnUrl() {
    return returnUrl;
  }


  public void setReturnUrl(String returnUrl) {
    this.returnUrl = returnUrl;
  }


  public PaymentSession secureStatus(String secureStatus) {
    
    this.secureStatus = secureStatus;
    return this;
  }

   /**
   * Get secureStatus
   * @return secureStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SECURE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecureStatus() {
    return secureStatus;
  }


  public void setSecureStatus(String secureStatus) {
    this.secureStatus = secureStatus;
  }


  public PaymentSession paymentLinkId(String paymentLinkId) {
    
    this.paymentLinkId = paymentLinkId;
    return this;
  }

   /**
   * Get paymentLinkId
   * @return paymentLinkId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_LINK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentLinkId() {
    return paymentLinkId;
  }


  public void setPaymentLinkId(String paymentLinkId) {
    this.paymentLinkId = paymentLinkId;
  }


  public PaymentSession paymentLinkGid(String paymentLinkGid) {
    
    this.paymentLinkGid = paymentLinkGid;
    return this;
  }

   /**
   * Get paymentLinkGid
   * @return paymentLinkGid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_LINK_GID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentLinkGid() {
    return paymentLinkGid;
  }


  public void setPaymentLinkGid(String paymentLinkGid) {
    this.paymentLinkGid = paymentLinkGid;
  }


  public PaymentSession mrn(String mrn) {
    
    this.mrn = mrn;
    return this;
  }

   /**
   * Get mrn
   * @return mrn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MRN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMrn() {
    return mrn;
  }


  public void setMrn(String mrn) {
    this.mrn = mrn;
  }


  public PaymentSession rrn(String rrn) {
    
    this.rrn = rrn;
    return this;
  }

   /**
   * Get rrn
   * @return rrn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RRN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRrn() {
    return rrn;
  }


  public void setRrn(String rrn) {
    this.rrn = rrn;
  }


  public PaymentSession paymentMethodType(List<PaymentMethodType> paymentMethodType) {
    
    this.paymentMethodType = paymentMethodType;
    return this;
  }

  public PaymentSession addPaymentMethodTypeItem(PaymentMethodType paymentMethodTypeItem) {
    if (this.paymentMethodType == null) {
      this.paymentMethodType = new ArrayList<>();
    }
    this.paymentMethodType.add(paymentMethodTypeItem);
    return this;
  }

   /**
   * Get paymentMethodType
   * @return paymentMethodType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PaymentMethodType> getPaymentMethodType() {
    return paymentMethodType;
  }


  public void setPaymentMethodType(List<PaymentMethodType> paymentMethodType) {
    this.paymentMethodType = paymentMethodType;
  }


  public PaymentSession paymentMethod(PaymentMethod paymentMethod) {
    
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentMethod getPaymentMethod() {
    return paymentMethod;
  }


  public void setPaymentMethod(PaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public PaymentSession currency(Currency currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Currency getCurrency() {
    return currency;
  }


  public void setCurrency(Currency currency) {
    this.currency = currency;
  }


  public PaymentSession customer(Customer customer) {
    
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Customer getCustomer() {
    return customer;
  }


  public void setCustomer(Customer customer) {
    this.customer = customer;
  }


  public PaymentSession accountRate(AccountRate accountRate) {
    
    this.accountRate = accountRate;
    return this;
  }

   /**
   * Get accountRate
   * @return accountRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountRate getAccountRate() {
    return accountRate;
  }


  public void setAccountRate(AccountRate accountRate) {
    this.accountRate = accountRate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentSession paymentSession = (PaymentSession) o;
    return Objects.equals(this.gid, paymentSession.gid) &&
        Objects.equals(this.createdAt, paymentSession.createdAt) &&
        Objects.equals(this.updatedAt, paymentSession.updatedAt) &&
        Objects.equals(this.deleted, paymentSession.deleted) &&
        Objects.equals(this.status, paymentSession.status) &&
        Objects.equals(this.amount, paymentSession.amount) &&
        Objects.equals(this.amountRefunded, paymentSession.amountRefunded) &&
        Objects.equals(this.amountUnCaptured, paymentSession.amountUnCaptured) &&
        Objects.equals(this.amountReceived, paymentSession.amountReceived) &&
        Objects.equals(this.description, paymentSession.description) &&
        Objects.equals(this.statementDescriptor, paymentSession.statementDescriptor) &&
        Objects.equals(this.receiptEmail, paymentSession.receiptEmail) &&
        Objects.equals(this.receiptSms, paymentSession.receiptSms) &&
        Objects.equals(this.confirmMethod, paymentSession.confirmMethod) &&
        Objects.equals(this.captureMethod, paymentSession.captureMethod) &&
        Objects.equals(this.errorCode, paymentSession.errorCode) &&
        Objects.equals(this.errorDescription, paymentSession.errorDescription) &&
        Objects.equals(this.refundReason, paymentSession.refundReason) &&
        Objects.equals(this.refundNote, paymentSession.refundNote) &&
        Objects.equals(this.disputeType, paymentSession.disputeType) &&
        Objects.equals(this.disputeStatus, paymentSession.disputeStatus) &&
        Objects.equals(this.respondBy, paymentSession.respondBy) &&
        Objects.equals(this.paymentDate, paymentSession.paymentDate) &&
        Objects.equals(this.refundDate, paymentSession.refundDate) &&
        Objects.equals(this.disputeDate, paymentSession.disputeDate) &&
        Objects.equals(this.amountDisputed, paymentSession.amountDisputed) &&
        Objects.equals(this.disputeFee, paymentSession.disputeFee) &&
        Objects.equals(this.feeAmount, paymentSession.feeAmount) &&
        Objects.equals(this.feeTax, paymentSession.feeTax) &&
        Objects.equals(this.net, paymentSession.net) &&
        Objects.equals(this.mdr, paymentSession.mdr) &&
        Objects.equals(this.receiptNumber, paymentSession.receiptNumber) &&
        Objects.equals(this.nextActionUrl, paymentSession.nextActionUrl) &&
        Objects.equals(this.psClientSecret, paymentSession.psClientSecret) &&
        Objects.equals(this.authorizationId, paymentSession.authorizationId) &&
        Objects.equals(this.returnUrl, paymentSession.returnUrl) &&
        Objects.equals(this.secureStatus, paymentSession.secureStatus) &&
        Objects.equals(this.paymentLinkId, paymentSession.paymentLinkId) &&
        Objects.equals(this.paymentLinkGid, paymentSession.paymentLinkGid) &&
        Objects.equals(this.mrn, paymentSession.mrn) &&
        Objects.equals(this.rrn, paymentSession.rrn) &&
        Objects.equals(this.paymentMethodType, paymentSession.paymentMethodType) &&
        Objects.equals(this.paymentMethod, paymentSession.paymentMethod) &&
        Objects.equals(this.currency, paymentSession.currency) &&
        Objects.equals(this.customer, paymentSession.customer) &&
        Objects.equals(this.accountRate, paymentSession.accountRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gid, createdAt, updatedAt, deleted, status, amount, amountRefunded, amountUnCaptured, amountReceived, description, statementDescriptor, receiptEmail, receiptSms, confirmMethod, captureMethod, errorCode, errorDescription, refundReason, refundNote, disputeType, disputeStatus, respondBy, paymentDate, refundDate, disputeDate, amountDisputed, disputeFee, feeAmount, feeTax, net, mdr, receiptNumber, nextActionUrl, psClientSecret, authorizationId, returnUrl, secureStatus, paymentLinkId, paymentLinkGid, mrn, rrn, paymentMethodType, paymentMethod, currency, customer, accountRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentSession {\n");
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amountRefunded: ").append(toIndentedString(amountRefunded)).append("\n");
    sb.append("    amountUnCaptured: ").append(toIndentedString(amountUnCaptured)).append("\n");
    sb.append("    amountReceived: ").append(toIndentedString(amountReceived)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    statementDescriptor: ").append(toIndentedString(statementDescriptor)).append("\n");
    sb.append("    receiptEmail: ").append(toIndentedString(receiptEmail)).append("\n");
    sb.append("    receiptSms: ").append(toIndentedString(receiptSms)).append("\n");
    sb.append("    confirmMethod: ").append(toIndentedString(confirmMethod)).append("\n");
    sb.append("    captureMethod: ").append(toIndentedString(captureMethod)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("    refundReason: ").append(toIndentedString(refundReason)).append("\n");
    sb.append("    refundNote: ").append(toIndentedString(refundNote)).append("\n");
    sb.append("    disputeType: ").append(toIndentedString(disputeType)).append("\n");
    sb.append("    disputeStatus: ").append(toIndentedString(disputeStatus)).append("\n");
    sb.append("    respondBy: ").append(toIndentedString(respondBy)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    refundDate: ").append(toIndentedString(refundDate)).append("\n");
    sb.append("    disputeDate: ").append(toIndentedString(disputeDate)).append("\n");
    sb.append("    amountDisputed: ").append(toIndentedString(amountDisputed)).append("\n");
    sb.append("    disputeFee: ").append(toIndentedString(disputeFee)).append("\n");
    sb.append("    feeAmount: ").append(toIndentedString(feeAmount)).append("\n");
    sb.append("    feeTax: ").append(toIndentedString(feeTax)).append("\n");
    sb.append("    net: ").append(toIndentedString(net)).append("\n");
    sb.append("    mdr: ").append(toIndentedString(mdr)).append("\n");
    sb.append("    receiptNumber: ").append(toIndentedString(receiptNumber)).append("\n");
    sb.append("    nextActionUrl: ").append(toIndentedString(nextActionUrl)).append("\n");
    sb.append("    psClientSecret: ").append(toIndentedString(psClientSecret)).append("\n");
    sb.append("    authorizationId: ").append(toIndentedString(authorizationId)).append("\n");
    sb.append("    returnUrl: ").append(toIndentedString(returnUrl)).append("\n");
    sb.append("    secureStatus: ").append(toIndentedString(secureStatus)).append("\n");
    sb.append("    paymentLinkId: ").append(toIndentedString(paymentLinkId)).append("\n");
    sb.append("    paymentLinkGid: ").append(toIndentedString(paymentLinkGid)).append("\n");
    sb.append("    mrn: ").append(toIndentedString(mrn)).append("\n");
    sb.append("    rrn: ").append(toIndentedString(rrn)).append("\n");
    sb.append("    paymentMethodType: ").append(toIndentedString(paymentMethodType)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    accountRate: ").append(toIndentedString(accountRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

