/*
 * Swirepay Payment API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client;

import com.swirepay.client.model.CustomerRequest;
import com.swirepay.client.model.CustomerResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerApi
 */
@Ignore
public class CustomerApiTest {

    private final CustomerApi api = new CustomerApi();

    
    /**
     * Add a customer
     *
     * Adds a customer to an account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addCustomerTest() {
        String xApiKey = null;
        CustomerRequest body = null;
        CustomerResponse response = api.addCustomer(xApiKey, body);

        // TODO: test validations
    }
    
    /**
     * Get customers
     *
     * Get customers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerTest() {
        String xApiKey = null;
        CustomerResponse response = api.getCustomer(xApiKey);

        // TODO: test validations
    }
    
}
