/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client;

import com.swirepay.client.model.PlanListResponse;
import com.swirepay.client.model.PlanRequest;
import com.swirepay.client.model.PlanResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlanApi
 */
@Ignore
public class PlanApiTest {

    private final PlanApi api = new PlanApi();

    
    /**
     * Add a new plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPlanTest() {
        PlanRequest planRequest = null;
        PlanResponse response = api.addPlan(planRequest);

        // TODO: test validations
    }
    
    /**
     * Get All Plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPlanTest() {
        Integer page = null;
        Integer size = null;
        PlanListResponse response = api.getAllPlan(page, size);

        // TODO: test validations
    }
    
    /**
     * Get Plan by Gid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getplanByGidTest() {
        String gid = null;
        PlanResponse response = api.getplanByGid(gid);

        // TODO: test validations
    }
    
    /**
     * Update Plan
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePlanTest() {
        String gid = null;
        PlanRequest planRequest = null;
        PlanResponse response = api.updatePlan(gid, planRequest);

        // TODO: test validations
    }
    
}
