/*
 * Swirepay API
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.swirepay.client;

import com.swirepay.client.model.SubscriptionListResponse;
import com.swirepay.client.model.SubscriptionRequest;
import com.swirepay.client.model.SubscriptionResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionApi
 */
@Ignore
public class SubscriptionApiTest {

    private final SubscriptionApi api = new SubscriptionApi();

    
    /**
     * Add a new subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSubscriptionTest() {
        SubscriptionRequest subscriptionRequest = null;
        SubscriptionResponse response = api.addSubscription(subscriptionRequest);

        // TODO: test validations
    }
    
    /**
     * Cancel Subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelSubscriptionTest() {
        String gid = null;
        String destinationAccount = null;
        SubscriptionRequest subscriptionRequest = null;
        SubscriptionResponse response = api.cancelSubscription(gid, destinationAccount, subscriptionRequest);

        // TODO: test validations
    }
    
    /**
     * Get All Subscription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSubscriptionTest() {
        Integer page = null;
        Integer size = null;
        String destinationAccount = null;
        SubscriptionListResponse response = api.getAllSubscription(page, size, destinationAccount);

        // TODO: test validations
    }
    
    /**
     * Get Subscription by Gid
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubscriptionByGidTest() {
        String gid = null;
        String destinationAccount = null;
        SubscriptionListResponse response = api.getSubscriptionByGid(gid, destinationAccount);

        // TODO: test validations
    }
    
}
